# Generated by Django 3.2.6 on 2021-08-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('noofpeople', models.IntegerField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('time', models.TimeField()),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
